### ISSUE TITLE
Unexpected results with option filter

### ISSUE THREAD

**Issue by olafveerman** [developmentseed/gep-explorer#115]
When applying a filter of type `option`, the Explorer shows no data.

To replicate:

1. Go to Malawi scenario
2. Deselect 'Mini-grid - Hydro' on the 'Electrification Technology (2030)

Expected behavior: no change in the result data, as mini grids are not part of the results.

What actually happened: `No data is available for this scenario. Please choose a different set of levers.`

cc @vgeorge @danielfdsilva

**Comment by danielfdsilva** [comment]
@olafveerman @vgeorge This happens because the the data has FinalElecCode as a float (like 3.0), and the rest of the system is using ints. Looking into what the best fix is

**Comment by vgeorge** [comment]
Already solved by updating source data.
