### ISSUE TITLE
Malawi map not loading

### ISSUE THREAD

**Issue by bpstewar** [developmentseed/gep-explorer#124]
http://gep-explorer.surge.sh/explore/mw-1

The web page is simply hanging for me - I tried it in both chrome and firefox from within the WBG network. Looking at the network traffic, the following link returns a message: "Tile Not Found"

https://api.mapbox.com/v4/devseed.2a5bvzlz/6/37/35.vector.pbf?access_token=pk.eyJ1IjoiZGV2c2VlZCIsImEiOiJjam9vamtjc2ExaHl2M3FxYW0yeTNjeHprIn0.EGNe0UbYK1gEQSB9Bs9YYw

Also, this request hangs as well

http://gep-data-service.us-west-2.elasticbeanstalk.com/scenarios/mw-1-0_0_0_0_0_0_0_0?year=2030

**Comment by vgeorge** [comment]
Hello @bpstewar, we are performing a ingest at the moment. I'll let you know we it's finished.

**Comment by vgeorge** [comment]
@bpstewar Can you please access the Explorer again? The ingest process was finished.

**Comment by vgeorge** [comment]
Closing this issue, the website is back online.
