### ISSUE TITLE
Test map in different browsers

### ISSUE THREAD

**Issue by vgeorge** [developmentseed/gep-explorer#22]
The application is being build and tested in Chrome. Its is necessary to also test in the following browsers:

- [ ] Edge
- [ ] Firefox
- [ ] Safari

**Comment by geohacker** [comment]
I used browserstack to test the map hosted on the surge url. I was looking for:

* Map interaction - zoom, pan, click on a feature
* Pop-up positioning - does the pop-up make itself visible 
* Filters

Windows 10:

* ✅ Edge 18 - latest
* ❌ IE 11 gets a 'Your browser is out-of-date'
* ✅ Firefox 64

Mac High Sierra:

* ✅Safari 11.1

Mac Mojave
* ✅Safari 12
* ✅Firefox 64
* ✅Firefox 63

**Comment by vgeorge** [comment]
Thats good to know, @geohacker, thank you. We still have to implement and deploy some changes on the interface, so I'll leave this issue until the last browser check.

**Comment by vgeorge** [comment]
The Explorer is working on all modern browsers (Chrome, Firefox, Edge, Safari)  and showing a warning message when opened in a non-supported browser, which directs the user to http://outdatedbrowser.com.
