### ISSUE TITLE
Highlight selected feature

### ISSUE THREAD

**Issue by olafveerman** [developmentseed/gep-explorer#82]
Depending on the shape of the feature, it can be hard to know where a cluster starts and stops. When clicking a feature, it would be useful to highlight it on the map.

cc @vgeorge @ricardomestre 

![image](https://user-images.githubusercontent.com/751330/50180717-61e37980-02d8-11e9-84a6-7f73c7a732d2.png)

**Comment by vgeorge** [comment]
The hover event is being fired without deboucing, which make its response to mouse move slow. I'll let this open until we fixed.
